apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  namespace: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      serviceAccountName: iam
      containers:
        - name: iam
          image: docker.io/DOCKERHUB_USER/iam:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: IAM_API_URL
              value: http://iam-api.iam-api.svc.cluster.local:3000
            - name: IAM_APPLICATION_NAME
              value: "iam"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
